#FROM gcr.io/kasten-images/aggregatedapis:5.5.7
#FROM gcr.io/kasten-images/auth:5.5.7
#FROM gcr.io/kasten-images/upgrade:5.5.7
#FROM gcr.io/kasten-images/controllermanager:5.5.7
#FROM gcr.io/kasten-images/crypto:5.5.7
#FROM gcr.io/kasten-images/bloblifecyclemanager:5.5.7
#FROM gcr.io/kasten-images/dashboardbff:5.5.7
#FROM gcr.io/kasten-images/vbrintegrationapi:5.5.7
#FROM gcr.io/kasten-images/executor:5.5.7
#FROM gcr.io/kasten-images/cephtool:5.5.7
#FROM gcr.io/kasten-images/frontend:5.5.7
#FROM gcr.io/kasten-images/emissary:5.5.7
FROM gcr.io/kasten-images/init:5.5.7
